### ISSUE TITLE
Návod pro stavbu TF-G2

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#21]
Pro vytvoření návodu je potřeba splnit tyto podúkoly:

- [ ] #28 Vygenerovat ikea obrázky
- [ ] #29 Připravit seznam dílů
- [ ] #30 Napsat text
- [ ] #31 Přeložit text do AJ
- [ ] #32 Ověřit správnost návodu (ideálně někym třetím) 
- [ ] #33 Vytvořit celkové fotky
- [ ] #34 Připravit TF šablonu

První návrh bude v tomto [dokumentu](https://docs.google.com/document/d/1igvYGKJX6zBisZoPiBTlhrPUBWr7crV5i_z_QplnqCA/edit?usp=sharing)

**Comment by kaklik** [comment]
Myslím, že každý tenhle bod by reálně měl mít svoje vlastní issue a tady by na ně měly být linky. A nebo by to měl být spíš samostatný projekt pod TF-G2

**Comment by roman-dvorak** [comment]
@kaklik samostatný projekt pro vytvoření dokumentů k TF-G2 jsem již vytvořil. Je tady: https://github.com/ThunderFly-aerospace/TF-G2/projects/1#card-38058176

Jednotlivé body tohoto issue jsem rozepsal na vlastní úkoly.

**Comment by kaklik** [comment]
Pokud je ale tohle issue rozepsané na jednotlivé úkoly roztřiděné v projektu, tak je tohle issue tím uzavřené, ne?
