### ISSUE TITLE
Aktualizace snímače otáček rotoru

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#64]
## TODO:
 - [X] Vyřešení umístění pcb TFPROBE do spodního dílu rotorové hlavy
 - [ ] Zarážka pro správné zastrčení PCB do dílu
 - [x] Zastínění reflexního senzoru, aby nemohl být snadno osvícen ze zadní strany
 - [x] Zvětšení tloušťky a eliminace děr ve stěnách bubínku, aby nemohlo dojít k prosvícení
 - [x] Vyřešení otvoru v horní sploštělé části
 - [x] Kapsa na samojistnou matku pro uchycení táhel serv.

<hr>

[Aktuální snímač otáček](https://github.com/ThunderFly-aerospace/TFRPM01) je použit v kombinaci s optickou závorou. 
Na TFRPM01B je přidán pull-up ?3k? a fototranzistor je připojený na stejný vstup jako se připojuje hallova sonda. 

Použitá optická závora je náhodného typu ze zásob Robozoru. Je připevněna na vertikální držák ložisek rotorové osy. Skrz závoru se otáčí kalíšek s děrovanými otvory. 

![image](https://user-images.githubusercontent.com/1194177/93757235-ad8e2a00-fc06-11ea-81c9-bc4d76d38b8d.png)

![image](https://user-images.githubusercontent.com/1194177/93757279-c1399080-fc06-11ea-8a76-556a3056f731.png)

Lepší řešení by zřejmě bylo upravit současnou kontrukci TFRPM01B, tak aby na PCB byla zároveň optozávora i hallova sonda. 
Tím by byla odststraněna nutnost připojení externího snímače. 

Celé PCB by pak mohlo být horizontálně [mezi rameny táhel](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/stl/888_1012.stl) k servům rotorové hlavy. Dolů z rotorové hlavy by tak vedl pouze čtyřžilovýkablík k I2C.

**Comment by kaklik** [comment]
V případě že by pro snímání otáček, byl použit reflexivní snímač, tak existují dva způsoby jeho použití. 

### Snímač umístěný rovnoběžně se směrem otáčení

V této pozici je vysílač a přijímač reflexivního snímače umístěn podélně se směrem rotace.  Což odpovídá následujícímu obrázku. Pohled na rotorovou hlavu ze zadní strany, kde plošný spoj se snímačem je uchycen mezi rameny táhel rotorové hlavy. 


![image](https://user-images.githubusercontent.com/1194177/97166035-e16bea80-1784-11eb-855e-44bfde7a383a.png)

### Snímač umístěný radiálně

V tomto umístění by vysílač a přijímač reflexního snímače byly orientovány v radiálním směru vůči ose rotace rotoru. 
Umístění je ilustrováno na následujícím obrázku, který reprezentuje pohled z boku na rotorovou hlavu.

![image](https://user-images.githubusercontent.com/1194177/97168639-0febc480-1789-11eb-81c4-d4b096cbe01c.png)


V obou případech je reflexivita bubínku zajištěna spodní plochou bubínku, která při tisku bude položena na tiskové podložce. 
V této ploše jsou tmavé otvory realizované dutinou, která může přecházet v celý objem bubínku. Na obrázcích výše jsou znázorněny příčky, které mají sloužit ke zpevnění bubínku vůči ose rotace.

**Comment by kaklik** [comment]
@roman-dvorak  
Tohle vypadá na to, že repozitář vůbec neobsahuje reálně použitou verzi měřícího děrovaného bubínku rotoru. 

![image](https://user-images.githubusercontent.com/1194177/97231060-3c303100-17db-11eb-80db-eab94831dcac.png)

**Comment by kaklik** [comment]
Zatím jsem vytvořil přípravu pro uchycení TFPROBE.

![tfprobe](https://user-images.githubusercontent.com/1194177/99882851-9e862100-2c23-11eb-9ac7-eb2afdace844.JPG)

**Comment by roman-dvorak** [comment]
@kaklik ... Jak se sem strká ta matka? :D

![obrazek](https://user-images.githubusercontent.com/5196729/100155004-ccc76300-2ea6-11eb-84d7-81870357b904.png)

Navrhoval bych vytvořit kapsu.

**Comment by roman-dvorak** [comment]
Při doražení PCB do konce, drážky PCB naráží na šroub. Děje se tak i v případě, že pod hlavou šroubu není podložka. 

Bylo by dobré, aby v drážce byla zarážka, která by definovala maximální zastrčení PCB bez toho, aby to naráželo do šroubu roll osy rotorové hlavy.

**Comment by kaklik** [comment]
Já úplně nemám nápad, jak zajistit, aby šlo rozmontovat Roll osu a přitom tam mohl zůstat ten PCB.  Předpokládal jsem že se ten PCB bude muset vyndavat. Protože při montáži tam dost vadí hřebínek který trčí dolů, jednoduché posunutí PCB výše proto moc nepomůže.

Co se týká řešení té lámací hlavy, tak jsem přemýšlel o rozdělení tohoto dilu na dva díly, které by se šroubovaly k sobě.  Tím by se po odlomení teoretecky nemusela odšroubovávat táhla k servům. 

S tím vkládáním matice šroubu je to blbý, ale nejsem si jistej, zda je možné v kombinaci s kapsou používat samojistnou matici.

**Comment by roman-dvorak** [comment]
> Já úplně nemám nápad, jak zajistit, aby šlo rozmontovat Roll osu a přitom tam mohl zůstat ten PCB. Předpokládal jsem že se ten PCB bude muset vyndavat. Protože při montáži tam dost vadí hřebínek který trčí dolů, jednoduché posunutí PCB výše proto moc nepomůže.

OK, neřešme to. Vyndat PCB není složité :) 

> Co se týká řešení té lámací hlavy, tak jsem přemýšlel o rozdělení tohoto dilu na dva díly, které by se šroubovaly k sobě. Tím by se po odlomení teoretecky nemusela odšroubovávat táhla k servům.
Jo, tohle je fajn nápad! Mělo by to být součástí #69 

> S tím vkládáním matice šroubu je to blbý, ale nejsem si jistej, zda je možné v kombinaci s kapsou používat samojistnou matici.
Navrhoval bych to zkusit. Protože jsem dneska zkoušel tu matku tam vložit a je to opravdu složité. 

>Při doražení PCB do konce drážky, PCB naráží na šroub. Děje se tak i v případě, že pod hlavou šroubu není podložka.
Tento problém nebude nastávat, protože PCB stejně nebude tak hluboko v dílu.

**Comment by kaklik** [comment]
Upravený bubínek s vnitřními zuby pro snímání otáček rotoru [TFRPM01B](https://github.com/ThunderFly-aerospace/TFRPM01) v kmbinaci s [TFPROBE](https://github.com/ThunderFly-aerospace/TFPROBE01).

https://user-images.githubusercontent.com/1194177/103105607-1edae000-462f-11eb-8e46-ee450d7dc4fb.mp4

**Comment by kaklik** [comment]
Ta zarážka na PCB TFPROBE momentálně postrádá význam, protože PCB musí být zaražený v drážce až k hlavě šroubu, aby to fungovalo správně..

**Comment by kaklik** [comment]
Poslední iterace vypadá takto:

![TFPROBE](https://user-images.githubusercontent.com/1194177/104857619-10c06c80-591a-11eb-8692-054f14743573.JPG)

Myslím, že řešení je již použitelné.  Další zlepšení je možné až po dalších úpravách jako je #69. 

Řešení je nyní kompatibilní s původní rotorovou hlavou TF-G2  @slimonslimon.

**Comment by kaklik** [comment]
Čidlo po posledních úpravách funguje i těsně vedle 60W žárovky. Test na přímém slunečním světle je potřeba ještě provést, ale domnívám se, že problém je vyřešen.

**Comment by kaklik** [comment]
Na základě poznatků z issue: https://github.com/ThunderFly-aerospace/TFRPM01/issues/10 to vypadá, že je potřeba zvýšit barevný kontrast měřícího kloboučku. 

Jedna z možností, jak to vyřešit je vzít nějaký "IR tmavý" materiál. Například modrou, nebo šedou a na kloboučku vytištěném z této barvy obarvit pouze měřící zuby bílou fixou.

**Comment by kaklik** [comment]
![Newfile18](https://user-images.githubusercontent.com/1194177/112758418-99304d00-8fee-11eb-8480-2adc7bd01db5.png)

**Comment by roman-dvorak** [comment]
Skvělé.. tohle vypadá, že půjde realizovat relativně snadno.

**Comment by kaklik** [comment]
U modrého kloboučku je situace o něco horší, kvůli nižší hodnotě maximální hodnoty napětí.  To je na hranici funkčnosti, těsně pod hodnotou 2V. Tuto situaci by bylo možné zlepšit snížením hodnoty pull-upů buď na TFPROBE, nebo na TFRPM. 

![Newfile19](https://user-images.githubusercontent.com/1194177/112761909-c1737800-8ffd-11eb-820e-6300eb76e875.png)

Nicméně i při současném nastavení, snímač ještě stále měří.  Jak je z grafu vidět, tak vysoká hodnota má trochu rozptyl, závislý na přesné poloze kloboučku. To je zřejmě způsobeno tím, že je měření provedeno na starší verzi kloboučku, která ještě nemá tak přesně umístěné zuby.  Je pravděpodobné, že s novou verzí by byl signál lepší.

**Comment by kaklik** [comment]
Vyzkoušel jsem ještě novou tvarovou úpravu kloboučku, která má eliminovat výše popsanou nedokonalost způsobenou vyosením zubů. V podstatě to zřejmě zlepšuje, ale ne výrazně. 

![Newfile20](https://user-images.githubusercontent.com/1194177/114064273-c0fa9d00-9899-11eb-89d0-21c6a3b6c7b6.png)

Způsob snímání ale pokládám za funkční.
