### ISSUE TITLE
Přední podvozek - tuhost odpružení

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#9]
Aktuální návrh zaního dvoukolého podvozku vypadá takto.

![image](https://user-images.githubusercontent.com/1194177/78604050-721ac180-7859-11ea-896e-77257adf681e.png)

Jeho hlavním problémem je nízká tuhost. Zároveň i současná poměrně vysoká hmotnost podvozku není úplně ideální.  Proto je potřeba tuhost zvýšit při zachování současného množství použitého materiálu. 

Řešením tohoto problému může být vytvoření "prolisů" v pružinách podvozku. 

![image](https://user-images.githubusercontent.com/1194177/78674513-003b8a00-78e4-11ea-8cbd-1c76fbe8fe54.png)

Protože prolis pravděpodobně nebude vhodné udělat po celé délce pružiny podvozku, tak by jeho umístění a délka na na pružině měla být parametrizovatelná. V obrázku výše označeno úhlem alfa, který navíc na pružině může být posouván. 

Návrh na tvar prolisu, který v podstatě zachovává aktuální množství materiálu je nakresleno v řezu A-A. 

Aktuální návrh pružiny podvozku je [zde](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/src/888_2002.scad)

**Comment by roman-dvorak** [comment]
Na vírníku TF-G1 bude tento díl použit jako přední podvozek.

**Comment by kaklik** [comment]
![image](https://user-images.githubusercontent.com/1194177/81104835-63383500-8f13-11ea-96d1-320fb8abd3df.png)

Návrh nového tvaru je správný.  Jen jím je teď potřeba nahradit původní rovný materiál, alespoň v nějaké části označené úhlem alfa na nákresu výše. 
Pro zjednodušení je ale asi možné tímto tvarem střechy nahradit celou tu část čtvrtkruhu - nejhorší co se stane, je že  ten podvozek bude příliš tuhý.

**Comment by kaklik** [comment]
Aktuálně v modelu vidím tohle: 

![image](https://user-images.githubusercontent.com/1194177/82935657-ae32ee80-9f8d-11ea-9fdf-42b2225ea905.png)

Což je přesně to, co je potřeba. :)

**Comment by kaklik** [comment]
Tak konstrukční změna je znatelným zlepšením. 
![99423279_2759773510919627_6567304170120937472_n](https://user-images.githubusercontent.com/1194177/83197668-1c1e1800-a13e-11ea-8330-68b2aacafdb2.jpg)

Ta tuhost ale stále zřejmě není dostatečná, takže musíme vymyslet, jak to zlepšit. :)

**Comment by roman-dvorak** [comment]
@RomanDCZ přišel s návrhem podvozku načrtnutém na následujícím obrázku

![20200528_202604](https://user-images.githubusercontent.com/5196729/83247890-81a4ef80-a1a4-11ea-8b75-d463490e1bf0.jpg)

Stěny by možná mohly být ještě tenčí než jsou v aktuálním návrhu. Ale bylo by potřeba to zase otestovat.

**Comment by kaklik** [comment]
Před návrhem tohoto bych možná ještě navrhoval zkusit více prolomit ten prolis v současném návrhu. Protože podle fotky mi to přijde stále dost placaté. 

Ty otvory v novém návrhu na obrázku výše by asi měly být zase trojúhelníkové podobně jako na trupu, aby se ty příčky nebortily.

**Comment by RomanDCZ** [comment]
Čau Romy, ten náhled je trochu zavádějící, protože tam je výška toho
nosníku příliš velká. Když to tak odhadnu, tak u trupu bych měl výšku
nosníku cca 15mm, stěny s poloviční tloušťkou a výřezy, žebra mezi stěnami
asi tak, jak máš na obrázku. Když by to bylo moc tuhé, praskalo by to.

Přijdeš domů? Zavolej mamce. Měj se.

Dne pá 29. 5. 2020 12:44 uživatel Jakub Kákona <notifications@github.com>
napsal:

**Comment by kaklik** [comment]
Protože se tohle issue moc nehýbe, tak by možná bylo lepší zvolit jinou technologii podvozku.  Další možnost je použití menších tištěných dílů a [pružinového drátu](https://obchod.lasermodely.cz/kovy/290-nerezovy-pruzinovy-drat.html#/97-prumer-3_mm).

V tomto případě by byly tištěny dva druhy dílů. Jeden pro uchycení podvozku k trupu vírníku a pak dva kusy dílu pro uchycení kolečka. Ty by v nejlepším případě měly být symetrické, aby nebylo nutné tisknout zvlášť díl pro levé a pravé kolečko.

Taková konstrukce by mohla být realizována následovně. Kdy dráty budou uříznuty na správnou délku a zalepí se do vytištěných dílů.  

![image](https://user-images.githubusercontent.com/1194177/85207056-803f9080-b326-11ea-9aef-b48fcb7a421d.png)

Každé kolečko by bylo uchyceno na dvojici drátů, Tím by jednak mělo být možné použít tenčí drát a zároveň se tím zvýší předozadní tuhost podvozku, což je záležitost s kterou měl problém vírník [Auto-G2](https://github.com/ThunderFly-aerospace/Auto-G2).

Při návrhu dílů je však nutné dbát na správné vedení tiskových vrstev.  Díl kolečka musí být tištěn tak, aby tiskové vrstvy byly v ose drátu. Tato tisková pozice je v obrázku naznačena v pravo nahoře.
U horního dílu, který drží podvozek a který nelze moc tisknout na bok, tak aby vrstvy byly v osách podvozkových drátů,  by tak měly být oblé přechody mezi válcovými držáky podvozkových drátů a montážní plochou. Tím je alespoň rozloženo namáhání vrstev přes výšku několika vrstev.

**Comment by kaklik** [comment]
Tak aktuálně navržená varianta, kterou kupodivu jde i docela snadno tisknout (až na jednu stranu, kde jsou prořezy hodně sesunuté). 

![image](https://user-images.githubusercontent.com/1194177/87559152-37c38a80-c6ba-11ea-8b75-713c43231245.png)

Tohle řešení má hodně zajímavé vlastnosti a v podstatě je kombinací přístupů navržených @Elizaa62  a @RomanDCZ . 

Tuhost tohoto řešení je podobná, nebo mírně větší, než prvního vytištěného návrhu. Neobsahuje ale proti původnímu návrhu téměř žádný materiál! 

Jsem si tak jistý, že nějakou změnou parametrů půjde dosáhnout ještě větší tuhosti.  Například by se mělo vyzkoušet: 

1. Ještě více prolomit střední část podvozku směrem na vnější stranu
2. Přidat symetrickou děrovanou strukturu i s vnitřní strany.

**Comment by Elizaa62** [comment]
1. Prořezy jsou posouvané vždy o určitý úhel
2. prolomení si  můžeš nastavit sám - proměnná "angle" - teď jsem ji nastavila na 55°, ale mám problém v tom,že při zmenšení úhlu je nutné prodloužit i ty koncovky, protože ten materiál bude přesahovat přes koncovky - tak jsem doplnila proměnnou "presah"
3. Jak to myslíš?

**Comment by kaklik** [comment]
Tak jsem vytiskl novou verzi: 

![image](https://user-images.githubusercontent.com/1194177/92006011-7c77b380-ed44-11ea-9688-a2bb27946622.png)

Je skutečně mnohem pevnější než předchozí, navíc jde vytisknout podstatně snadněji (zkoušel jsem tisknout dva kusy). 
Nové poznatky, které díky tomu máme jsou: 

1. Tuhost pro dosednutí vírníku je teď už myslím dostatečná
2. Zřejmě by bylo vhodné aby podvozková noha byla skutečně úplná čtvrtkružnice (nebo i trošku více)- Nyní je to tak, že chybí několik stupňů do stavu, že  kolečko bude bez zatížení rovně k povrchu. Teď je bez zatížení přikloněné k vírníku. Zde si dokonce myslím, že kolečka by bez zatížení měla být naopak mírně vykloněna, aby při zatížení podvozku čistě hmotností vírníku byla kolmo k zemi. 
3. Je možná problém s nízkou torzní tuhostí podvozku protože je poměrně snadné podvozkovou nohu takhle ohnout: 

![image](https://user-images.githubusercontent.com/1194177/92006701-5c94bf80-ed45-11ea-8f73-50e5a707e49b.png)

To by ale možná mohla zlepšit myšlenka z bodu 3. výše. Kdy jsem zvažovat průřez podvozkovou nohou symetricky zdvojit. Nějak takhle:

**Comment by Elizaa62** [comment]
2. pro délku té kružnice tam asi slouží ta funkce "suspension_camber" z hodnoty 10 jsem ji snížila na hodnotu 2.
--> přidala jsem i ty výřezy.

3. udělám po víkendu

**Comment by kaklik** [comment]
Ad 2.  s tou délkou myslím budeme ještě několikrát hýbat.  Protože bude potřeba naladit délku tak, aby při zatížení vírníkem bylo kolečko právě kolmo k zemi.  Takže by se hodilo vyřešit nějak to automatický generování výřezů, aby se to nemuselo stále ručně kopírovat. ;)

Po víkendu budeme vědět více o tom jak se tohle řešení chová.  Dnes to vytisknu a někdy zítra namontujem na vírník.

**Comment by kaklik** [comment]
Po montáži na vírník se ukázalo, že nová úprava podvozku má o hodně menší předozadní tuhost.  Podvozková noha se tak snadno kroutí ve směru otáčení koleček.  
Pomoct by tomu mohlo přidání symetrické vnitřní struktury zmíněné výše.   V případě, že to dostatečně nepomůže, tak by zřejmě šlo podvozkovou nohu nahoru směrem k trupu postupně rozšiřovat. 

![118796106_695418411184435_8227266649249074609_n](https://user-images.githubusercontent.com/1194177/92386612-65560e80-f114-11ea-9a94-158e720e0f95.jpg)

![118821032_3080086042114458_1203194890467958743_n](https://user-images.githubusercontent.com/1194177/92386638-73a42a80-f114-11ea-9ef0-95755ab26c75.jpg)

**Comment by Elizaa62** [comment]
Hotovo

**Comment by kaklik** [comment]
Nové řešení s výztuhou z vnitřní strany funguje mnohem lépe a vírník na novém podvozku je bez problémů schopen stát. 


Potíž vzniká při přistání, kdy dojde ke zvýšenému předozadnímu namáhání podvozku. V takové situaci se obvykle podvozková noha vykroutí dozadu poblíž uchycení na trup vírníku. 




Řešením by zřejmě bylo postupné rozšíření podvozkové nohy od kolečka ke trupu, tak aby nejvíce na krut namáhaná část (u trupu), byla zároveň nejširší.  Rozšíření bych navrhoval realizovat jen v jedné ose ve směru délky trupu vírníku. 

![PTDC0005](https://user-images.githubusercontent.com/1194177/93769020-935e4700-fc1a-11ea-86ba-d6bab26d432d.JPG)

**Comment by slimonslimon** [comment]
![sesikmena_noha](https://user-images.githubusercontent.com/9033168/94673490-18cab100-0317-11eb-9cb2-79f073468bb9.png)

je to vyrvane z puvodního zdrojaku a upravené - pozor i čast označená jako původní zdrojak je upravená.

[sesikmena_noha.txt](https://github.com/ThunderFly-aerospace/TF-G2/files/5304734/sesikmena_noha.txt)

**Comment by Elizaa62** [comment]
Použila jsem Vítkův nápad.. bohužel mi funguje pouze pro jednu stranu - zelená část. Pro tu modrou část funguje, ale z mě nevysvětlitelného důvodu mi části nesedí k sobě.. a už fakt nevím, co s tím...

**Comment by slimonslimon** [comment]
Zdá se mi, že to totiž není vůbec jednoduché, dokonce zda je to vůbec řešitelné s tou vnitřní stranou... ale možná to jen nevidím

rychlý a možná funkční workround by byl udělat tu vnitřní stranu palcatou (nevím zda to někdo zkoušel nebo ne, já mám něco takového na jedné verzi nohou udělané z tvrdého papíru) - že by řezem té nohy byl  trojúhelník... samozřejmně s prořezy, které papír nemá

![IMG_20200913_150811](https://user-images.githubusercontent.com/9033168/94900627-974d5d00-0495-11eb-8f40-0aea5b891db4.jpg)

**Comment by slimonslimon** [comment]
aaha, tak, řešení existuje...

[sesikmena_noha_2.txt](https://github.com/ThunderFly-aerospace/TF-G2/files/5316715/sesikmena_noha_2.txt)

místo ořezávání excentrickým válcem, je potřeba ořezávat excentrickými kužely, které pak budou vnějším pláštěm toho vnitřku.

![sesikmena noha 2](https://user-images.githubusercontent.com/9033168/94902538-9f5acc00-0498-11eb-9494-45d8f74979d5.png)

**Comment by kaklik** [comment]
Aha super! :)

Ta vnitřní placatá strana, je sice workaround pro teď. Nicméně ta tuhost podvozku s placatou vnitřní stranou bude myslím nižší, než s tou příhradovou konstrukcí z vnitřní strany.  Neboť tady při kroucení podvozku se prakticky nemění ta příčná vzdálenost na vnitřní straně. 

Z toho mi vyplývá, že tu symetrickou vnitřní stranu potřebujem  (i kdyby měla mít tupější úhel než ta vnější).

**Comment by slimonslimon** [comment]
zdá se, že úhel otočení, aby byla noha tisknutelná se dá zjistit z bočního nárysu, kdy kužele přejdou do trojůhelníků.

Docela mne děsí různé závislosti parametrů.

**Comment by kaklik** [comment]
No ještě existuje jedna možnost jak tu podvozkovou nohu zkonstruovat.  Myslím, že by to šlo za použití téhle knihovny: https://www.thingiverse.com/thing:900137#files

Pak by průřez nohy nebyl kosočtverec, ale airfoil..    Problém s natočením nohy pro tisk se tím ale určitě neřeší, naopak zesložiťuje, neboť airfoil by pak musel být levý a pravý. Ještě k tomu by se zřejmě musela splacatit třeba náběžná nebo odtoková hrana, aby to bylo na co položit při tisku.

**Comment by slimonslimon** [comment]
to je dle mého názoru cesta do pekla

**Comment by kaklik** [comment]
> to je dle mého názoru cesta do pekla

Z jakého důvodu?

**Comment by slimonslimon** [comment]
> > to je dle mého názoru cesta do pekla
> 
> Z jakého důvodu?

Po osbní konzultaci vyšlo najevo, že jsem úplně nepochopil jak chtěl @kaklik tu knihovnu použít.

**Comment by kaklik** [comment]
@Elizaa62 @slimonslimon Pokračujte prosím nějak ve spolupráci na řešení toho podvozku tou původní metodou.   Já se výhledově pokusím udělat nějaký tvarový prototyp za pomoci té NACA sweep knihovny.  Nemyslim si totiž, že je to nějak zjevně snažší řešení toho problému (Protože už jen kvůli tisku se tam bude muset nějak upravovat asi odtoková hrana a natáčet na ní).  Zkusím to nejdřív ověřit.

**Comment by slimonslimon** [comment]
@Elizaa62 co nějaká schůzka a tam to probrat? (mimochodem, všechno nejlepší k svátku)

Zabývám se také myšlenkou, kterou naznačil a navrhnul @roman-dvorak, a to je konstkrukce pomocí uhlíkových tyček. Návrh jejich upnutí by totiž byl poměrně jednoduchý. v podstatě to co psal @kaklik tady:
https://github.com/ThunderFly-aerospace/TF-G2/issues/9#issuecomment-647020654

**Comment by Elizaa62** [comment]
Pokusila jsem se o aktualizaci pomocí návrhu sesikmene_nohy_2.. přidala jsem i prořezy
![image](https://user-images.githubusercontent.com/31339298/95379780-20c1bc80-08e6-11eb-9c51-84672813a8df.png)

**Comment by kaklik** [comment]
![image](https://user-images.githubusercontent.com/1194177/95623840-3e259080-0a76-11eb-83b1-b0c86d06a89f.png)

Tvar podvozku již funguje správně, ale aby podvozková noha šla použít, tak stále vyžaduje některé úpravy. 

- [ ] Tvar by měl být dutý, aby měla nízkou hmotnost,  tak jak to bylo před úpravou rozšířením
- [ ] Odlehčovací trojúhelníku musí měnit podél délky nohy svojí výšku, aby tloušťka všech stěn zůstávala zachována
- [ ] Podvozkovou nohu je potřeba alespoň z jedné strany sploštit, aby ji bylo možné tisknout položenou na podložce.  Tento krok zahrnuje otočení zužující se strany podvozkové nohy rovnoběžně s podložkou.

**Comment by Elizaa62** [comment]
1. Dutost - parametr "zmenseni"
2. změna trojúhelníku - to nevím, jak udělat
3. splošení - to si nedokážu představit

**Comment by kaklik** [comment]
>     1. Dutost - parametr "zmenseni"

Jo, to se docela povedlo! I jsem si vyzkoušel, že to funguje a dělá to co potřebujem. 

Na začátek jsem tam připsal do komentářů návrhy na nové hodnoty, neboť ta patka za k terou se podvozková noha přimontovává k vírníku se musí zvětšit. Když jsem to ale udělal, tak se to trochu rozsypalo. Takže jsem ty hodnoty vrátil zpátky a ty požadované jsem nechal v kometářích.

> 
>     2. změna trojúhelníku - to nevím, jak udělat

Zkusil jsem ti do jednoho toho for cyklu dopsat příklad, jak by to zhruba mohlo jít vyřešit. 
Mění to parametr průměru, pomocí kterého se vytváří ty trojuhelníky. Ty parametry, které jsem tam dopsal jsou jen pokus, správnější by zřejmě bylo je nějak chytřeji spočítat. 
Teď ale zřejmě nevadí že budou odhadnuté. (jen by to bylo potřeba udělat rovnou na tu rozšířenou nohu, viz výše.)

> 
>     3. splošení - to si nedokážu představit

Tady jsem udělal trochu obrázek toho, jak se to má tisknout.  Čevnený kvádr odpovídá tiskové podložce na kterou je ta podvozková noha položena při tisku. Ve tvém prvním návrhu, byla tahle strana zploštěná (uříznutá kovádrem), aby to na podložce drželo. To je myslím stále rozumný způsob jak to vyřešit. V tomhle návrhu ale tehlenhle uřezávací kvádr zatím chybí. V důsledku toho pak na podložku vychází ostrá hrana, která na tiskové podložce nebude držet. 

![image](https://user-images.githubusercontent.com/1194177/96895495-c4859d80-148c-11eb-9c89-8329be66e3ce.png)

Tenhle obrázek ukazuje, že je podvozková noha navíc trošku otočená, aby bylo na podložku sedělo. Tohle otočení bych navrhoval dělat až v [tomhle tiskovém souboru](https://github.com/ThunderFly-aerospace/TF-G2/blob/debbf4c73f28c2ae5a0a2d58d68ac2b3ddb91d1a/CAD/src/printplate/printplate_888_2002.scad#L6-L7). Zatím tam jsou opět nějaké odhadnuté hodnoty.

**Comment by kaklik** [comment]
Pokusím se shrnout aktuální stav, aby tohle issue bylo zas trochu přehledé

* Máme a aktuálně používáme [tuto verzi](https://github.com/ThunderFly-aerospace/TF-G2/issues/9#issuecomment-696098022) tato verze by potřobavala upravit pro větší odolnost proti vylomení při přistání. Vylomení je způsobeno předozadním zkroucením podvozku.  Existuje předpoklad, že k vyřešení tohoto problému by stačilo podvozkovou nohu rozšířit směrem ke trupu vírníku - na této úpravě už @Elizaa62  a @slimonslimon odvedli část práce.  Stav je viditelný z postů výše.
* V mezičase vznikly návrhy na dvě další konstrukční řešení podvozku, které ale nebyly zatím realizovány v žádné podobě. 
    1. [Konstrukce založená na aerodynamickém profilu ](https://github.com/ThunderFly-aerospace/TF-G2/issues/9#issuecomment-702710622) - jde spíše o řešení konstrukčních obtíží s návrhem podvozku v OpenSCADu než o významně odlišnou realizaci.
    2. [Konstrukční řešení využivající pružinové dráty](https://github.com/ThunderFly-aerospace/TF-G2/issues/9#issuecomment-647020654) - zde by pružnost vytištěných dílů byla nahrazena absorbcí energie v pružinových drátech, které by byly zalepeny do vytištěných dílů. 
    3. Kostrukční řešení využívající uhlíkové tyčky - v tomto případě je konstrukce velmi podobná jako v případě pružinových drátů, akorát vzhledem k tomu, že uhlíkový profil není schopen absorbovat významné množství energie svým ohybem, tak by uložení trubek podvozku muselo být otočné a absorbce energie řešena nějakým externím absorberem (guma, píst, tlumič). Toto řešení se technicky velmi podobá aktuálnímu podvozku na TF-G1.

**Comment by kaklik** [comment]
@JanKott  To zplacatění, kvůli tisku, které je v modelu aktuálně implementováno: 

![image](https://user-images.githubusercontent.com/1194177/104454811-b1bfc800-55a6-11eb-8f0b-f95945874fc3.png)

Způsobuje, že na straně podvozku u podložky, není prakticky žádný materiál.  Myslím si, že by bylo potřeba, aby zde byla téměř kontinuální tloušťka materiálu, aby tisková vlákna byla spojitá přes celou délku podvozkové nohy.

**Comment by JanKott** [comment]
Vrátil jsem díru přes celou patku pro šroub kolečka.
Zmenšil jsem trojúhelníky aby zůstalo více materiálu na horním a spodním (z pohledu tisku) okraji podvozku.
Ořez pro položení na podložku jsem zrcadlil i na druhou stranu nohy aby byla symetrická.

Otočení trojúhelníků jsem zatim neřešil. Když je jen pootočim tak se mi ten problém s tloušťkou jen přesune jinam.

**Comment by kaklik** [comment]
Pokusil jsem se to vytisknout a skončil jsem na tomto problému: 

![20210121_212944](https://user-images.githubusercontent.com/1194177/105410646-8a19d100-5c32-11eb-8f52-070049ffb6b2.jpg)

Je to způsobené tím, že současný [print-plate](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/src/printplate/printplate_888_2002.scad) neřeší rotaci vůči podložce. Podvozková noha se tak tiskne do vzduchu. 

Druhá věc pak je, že současné uchycení kolečka je myslím zbytečně hluboké a bylo by nutné použít zbytečně dlouhý šroub. Myslím že je dostatečné, aby uchycení bylo stejně hluboké, jako je tloušťka příhradové části s trojůhelníky.

![image](https://user-images.githubusercontent.com/1194177/105411505-c3067580-5c33-11eb-8e80-11be1209f391.png)

**Comment by JanKott** [comment]
Otočil jsem díl aby seděl na podložku a zmenšil podvozkový blok.

**Comment by kaklik** [comment]
Při tisku se mi stala taková nepříjemnost, že z podvozku vzniklo něco jako siamská dvojčata. :D 

![20210202_191709](https://user-images.githubusercontent.com/1194177/106671026-225a7300-65ae-11eb-93c8-bcd57d589180.jpg)

Tiskovou soustavu jsem ale opravil a už se tiskne nová verze i se vzdálenějšími otvory pro šrouby.  Nicméně si myslím, že tahle kostrukce podvozkové nohy bude už úplně v pohodě, ta tuhost je výtečná do všech směrů.  :)

**Comment by kaklik** [comment]
Tak řešení podvozku se při posledních letech docela osvědčilo. :) 

Při "přistání" sice došlo k utržení podvozkové nohy od kostky, která podvozkovou nohu drží na šroubech. Ale řešení tohoto detailu jednak už není přímo předmětem tohoto issue a potom tato přistání asi nelze považovat za úplně relevatní k tomu co podvozek má vydržet.

**Comment by slimonslimon** [comment]
dobrá práce @JanKott
